테스트 코드 작성
team-culfare/YWC-SERVER pull request #12
Opened 2023-06-20 08:12 UTC by woomae

- 전남 시군 모든지역에 대해 필터링 테스트

2023-06-20 14:44 UTC, lightpurple requested changes

2023-06-20 14:44 UTC, lightpurple commented on test/integration/stores.test.ts
> +            for (const city of cities) {
for문을 통해 모든 city에 대해 request를 보내는 것보단 faker.helpers.arrayElement 를 사용해서 랜덤한 city에 대해 확인하는 것도 좋아보입니다.

2023-06-20 14:44 UTC, lightpurple commented on test/integration/stores.test.ts
> +                        q: storeName,
지금 해당 city에 storeName을 가진 가맹점을 조회하는 거 같은데 지금 테스트 목적이 모든 city에 해당 storeName을 가진 가맹점이 있는 걸 테스트하는게 아니라 request에 city 변수를 입력했을때 해당 city의 가맹점들만 응답하는지 테스트를 하는 거기 때문에 테스트 목적에 맞게끔 수정이 필요해 보입니다.

2023-06-22 04:11 UTC, woomae commented on test/integration/stores.test.ts
> +            for (const city of cities) {
알겠습니다!

2023-06-22 04:12 UTC, woomae commented on test/integration/stores.test.ts
> +                        q: storeName,
제가 잘못 이해하고 있었네용...ㅎㅎ
덕분에 q파라미터 없이 검색하는 로직 부분에서 문제를 찾았습니다 수정하겠습니다!!!

2023-06-23 01:17 UTC, lightpurple approved these changes

2023-06-23 01:21 UTC, JDW611 approved these changes

2023-06-23 04:59 UTC, merged